steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - asia-south1-docker.pkg.dev/$PROJECT_ID/harsha-swiggy-repo/swiggy:$SHORT_SHA
      - .

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - asia-south1-docker.pkg.dev/$PROJECT_ID/harsha-swiggy-repo/swiggy:$SHORT_SHA

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - swiggy
      - --image=asia-south1-docker.pkg.dev/$PROJECT_ID/harsha-swiggy-repo/swiggy:$SHORT_SHA
      - --region=asia-south1
      - --platform=managed
      - --allow-unauthenticated
      - --no-traffic

  # Canary rollout step
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
    - -c
    - |
      LATEST=$(gcloud run services describe swiggy \
        --region=asia-south1 \
        --format='value(status.latestReadyRevisionName)')

      PREV=$(gcloud run services describe swiggy \
        --region=asia-south1 \
        --format='value(status.traffic[0].revisionName)')

      gcloud run services update-traffic swiggy \
        --to-revisions=$LATEST=10,$PREV=90 \
        --region=asia-south1

options:
  logging: CLOUD_LOGGING_ONLY
